language: php
sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --ignore-platform-reqs --dev --prefer-dist --no-interaction

script:
  - bin/phing ci
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then bin/phing phpmd; fi;'

after_script:
  - echo $TRAVIS_PHP_VERSION
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" == "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
