language: php
sudo: false
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --ignore-platform-reqs --dev --prefer-dist --no-interaction

script:
  - bin/phing ci
