language: php
sudo: false
matrix:
  include:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
  allow_failures:
    - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --ignore-platform-reqs --dev --prefer-dist --no-interaction

script:
  - bin/phing ci

after_script:
  - echo $TRAVIS_PHP_VERSION
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
